version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
                - "8000:80"
        volumes:    
            - ./var/nginx:/etc/nginx/:ro
            - ./var/nginx/logs:/var/log/nginx
        networks:
            - production-network
        depends_on:
            - "spring1"
            - "spring2"
    mysql:
        image: mysql
        container_name: mysql
        networks:
            - production-network
        environment:    
            MYSQL_ROOT_PASSWORD: "3j3b4ig4"
            MYSQL_DATABASE: "root"
        
    spring1:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring1
        ports:
                - "8080:8081"
        volumes:
            - ./var:/var
        networks:
            - production-network
        depends_on:
            - "mysql"
    spring2:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring2
        ports:
                - "8081:8081"
        volumes:
            - ./var:/var 
        networks:
            - production-network
        depends_on:
            - "mysql"
networks:
    production-network:
        driver: bridge
