version: '3'
services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
                - "8000:80"
        volumes:    
            - ./var/nginx:/etc/nginx/:ro
            - ./var/nginx/logs:/var/log/nginx
        networks:
            - production-network
        depends_on:
            - "spring1"
            - "spring2"
    mysql:
        image: mysql
        container_name: mysql
        networks:
            - production-network
        environment:    
            MYSQL_ROOT_PASSWORD: "3j3b4ig4"
            MYSQL_DATABASE: "root"
        
    spring1:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring1
        ports:
                - "8080:8081"
        volumes:
            - ./var:/var
        networks:
            - production-network
        depends_on:
            - "mysql"
    spring2:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring2
        ports:
                - "8081:8081"
        volumes:
            - ./var:/var 
        networks:
            - production-network
        depends_on:
            - "mysql"
    rabbitmq:
        image: rabbitmq:3-management
        command: ['rabbitmq-server', '--hostname', 'localhost', '--name', 'integracao']
        restart: always
        ports:
            - '5672:5672'
            - '8082:15672'
        volumes:
            - ./var/rabbitmq/plugins:/tmp   
            - ./var/rabbitmq:/var/lib/rabbitmq
            - /etc/localtime:/etc/locatime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: 3j3b4ig4
networks:
    production-network:
        driver: bridge
