version: '3'
services:  						     
    nginx:                                                    							
        build:								
            dockerfile: ./docker/nginx.dockerfile		
            context: .						
        image: douglasq/nginx					
        container_name: nginx					
        ports:
            - "80:80"						
        networks:
            - production-network				
        depends_on: 						
            - "spring1"
            - "spring2"
    mysql:
        image: mysql
        networks:
            - production-network
    environment:
        MYSQL_PASSWORD: 3j3b4ig4
        
    spring1:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring1
        ports:
            - "8081:8081"
        networks:
            - production-network
        depends_on:
            - "mysql"
    spring2:
        image: docker.io/rafael3423/projeto_spring
        container_name: spring2
        ports:
            - "8082:8081"
        networks:
            - production-network
        depends_on:
            - "mysql"
networks: 			
    production-network:		
        driver: bridge		
